name: TeamTwo.CloudShield.Shield
on:
  push:
    branches: [ master ] 
    paths:
    - './src/TeamTwo.CloudShield.Shield.sln'
    - './src/TeamTwo.CloudShield.Shield/*'
    - '.github/workflows/shield-build.yml'   
  pull_request:
    branches: [ master ]
    paths:
    - './src/TeamTwo.CloudShield.Shield.sln'
    - './src/TeamTwo.CloudShield.Shield/*'
    - '.github/workflows/shield-build.yml'   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2
- name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore 
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal