name: TeamTwo.CloudShield.Shield

on:
  push:
    branches: [ master ] 
    paths:
    - './src/TeamTwo.CloudShield.Shield.sln'
    - './src/TeamTwo.CloudShield.Shield/*'
    - '.github/workflows/shield-build.yml'   
  pull_request:
    branches: [ master ]
    paths:
    - './src/TeamTwo.CloudShield.Shield.sln'
    - './src/TeamTwo.CloudShield.Shield/*'
    - '.github/workflows/shield-build.yml'   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: set environment variables
      uses: allenevans/set-env@v1.0.0
      with:
        TEAMTWO_SHIELDSOURCE: '/src/TeamTwo.CloudShield.Shield/TeamTwo.CloudShield.Shield.sln'    
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
      working-directory: '/src/TeamTwo.CloudShield.Shield/TeamTwo.CloudShield.Shield.sln' 
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: '/src/TeamTwo.CloudShield.Shield/TeamTwo.CloudShield.Shield.sln'
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: $TEAMTWO_SHIELDSOURCE
