name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v2
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.3
      with: 
        projectKey: HitzSPB_project_shield-poc
        orgnization: sonarcloud-hitzspb
        hostUrl: https://sonarcloud.io/
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./src/TeamTwo.CloudShield.Shield.sln
    - name: Test
      run: dotnet test --no-restore --verbosity normal
